package KieRule;
import com.rb.rules.entity.Order;

rule "HDFC"
when
orderObject : Order(cardType=="HDFC" && price>10000);
then
orderObject.setDiscount(10);
System.out.println( "HDFC " +orderObject.getName() );
end;

rule "ICICI"
when
orderObject : Order(cardType=="ICICI" && price>15000);
then
orderObject.setDiscount(8);
System.out.println( "ICICI" );
end;

rule "DBS"
when
orderObject : Order(cardType=="DBS" && price>15000);
then
orderObject.setDiscount(15);
System.out.println( "DBS" );
end;